import { useLanguage } from "@/i18n/LanguageProvider";
import type { Locale } from "@/i18n/translations";

export const devAdminCopy: Record<Locale, { title: string; description: string; notFound: string; noServer: string; ready: string; failed: string; heading: string; intro: string; name: string; email: string; password: string; secret: string; submit: string }> = {
  en: { title: "Internal admin setup — RoomEasy", description: "Internal-only screen used to create a test administrator.", notFound: "Not found.", noServer: "No server address is configured, so no account can be created.", ready: "Administrator ready — opening the back office.", failed: "The administrator could not be created.", heading: "Create a test administrator", intro: "Internal screen. It creates the account on the connected server (or promotes an existing one), signs you in and opens the back office. Unavailable in production.", name: "Full name", email: "Email", password: "Password", secret: "Dev admin secret", submit: "Create administrator and open the back office" },
  fr: { title: "Configuration administrateur interne — RoomEasy", description: "Page interne pour créer un administrateur de test.", notFound: "Page introuvable.", noServer: "Aucun serveur n'est configuré : impossible de créer un compte.", ready: "Administrateur prêt — ouverture de l'administration.", failed: "Impossible de créer l'administrateur.", heading: "Créer un administrateur de test", intro: "Page interne. Elle crée le compte sur le serveur connecté (ou promeut un compte existant), vous connecte et ouvre l'administration. Indisponible en production.", name: "Nom complet", email: "E-mail", password: "Mot de passe", secret: "Secret d'administration de test", submit: "Créer l'administrateur et ouvrir l'administration" },
  es: { title: "Configuración interna del administrador — RoomEasy", description: "Página interna para crear un administrador de prueba.", notFound: "Página no encontrada.", noServer: "No hay un servidor configurado, por lo que no se puede crear una cuenta.", ready: "Administrador listo — abriendo la administración.", failed: "No se pudo crear el administrador.", heading: "Crear un administrador de prueba", intro: "Página interna. Crea la cuenta en el servidor conectado (o asciende una existente), inicia sesión y abre la administración. No disponible en producción.", name: "Nombre completo", email: "Correo electrónico", password: "Contraseña", secret: "Clave de administrador de prueba", submit: "Crear administrador y abrir la administración" },
  de: { title: "Interne Administratoreinrichtung — RoomEasy", description: "Interne Seite zum Erstellen eines Testadministrators.", notFound: "Nicht gefunden.", noServer: "Keine Serveradresse konfiguriert; ein Konto kann nicht erstellt werden.", ready: "Administrator bereit — Verwaltung wird geöffnet.", failed: "Der Administrator konnte nicht erstellt werden.", heading: "Testadministrator erstellen", intro: "Interne Seite. Erstellt das Konto auf dem verbundenen Server (oder stuft ein bestehendes hoch), meldet Sie an und öffnet die Verwaltung. In der Produktion nicht verfügbar.", name: "Vollständiger Name", email: "E-Mail", password: "Passwort", secret: "Testadministrator-Schlüssel", submit: "Administrator erstellen und Verwaltung öffnen" },
  pt: { title: "Configuração interna do administrador — RoomEasy", description: "Página interna para criar um administrador de teste.", notFound: "Página não encontrada.", noServer: "Não existe um servidor configurado, pelo que não é possível criar uma conta.", ready: "Administrador pronto — a abrir a administração.", failed: "Não foi possível criar o administrador.", heading: "Criar um administrador de teste", intro: "Página interna. Cria a conta no servidor ligado (ou promove uma conta existente), inicia sessão e abre a administração. Indisponível em produção.", name: "Nome completo", email: "E-mail", password: "Palavra-passe", secret: "Chave de administrador de teste", submit: "Criar administrador e abrir a administração" },
};

export function useDevAdminCopy() {
  const { locale } = useLanguage();
  return devAdminCopy[locale];
}