/**
 * Reference data the application needs in order to behave correctly, and a
 * small set of demo accounts for local development.
 *
 * Everything here is inserted idempotently (`ON CONFLICT DO UPDATE/NOTHING`),
 * so the seed can be re-run at any time without creating duplicates.
 */

export type EquipmentSeed = {
  id: string;
  group:
    | "general"
    | "wellness"
    | "food"
    | "activities"
    | "transport"
    | "services"
    | "family"
    | "safety"
    | "cleaning"
    | "access";
  labelEn: string;
  labelFr: string;
  paid?: boolean;
};

/** The amenity catalogue shown in the listing wizard and the search filters. */
export const EQUIPMENT_SEED: EquipmentSeed[] = [
  { id: "swimming-pool", group: "general", labelEn: "Swimming pool", labelFr: "Piscine" },
  { id: "children-s-pool", group: "general", labelEn: "Children's pool", labelFr: "Piscine pour enfants" },
  { id: "garden", group: "general", labelEn: "Garden", labelFr: "Jardin" },
  { id: "terrace", group: "general", labelEn: "Terrace", labelFr: "Terrasse" },
  { id: "sun-terrace", group: "general", labelEn: "Sun terrace", labelFr: "Terrasse bien exposée" },
  { id: "non-smoking-rooms", group: "general", labelEn: "Non-smoking rooms", labelFr: "Chambres non-fumeurs" },
  { id: "family-rooms", group: "general", labelEn: "Family rooms", labelFr: "Chambres familiales" },
  { id: "air-conditioning", group: "general", labelEn: "Air conditioning", labelFr: "Climatisation" },
  { id: "heating", group: "general", labelEn: "Heating", labelFr: "Chauffage" },
  { id: "lift", group: "general", labelEn: "Lift", labelFr: "Ascenseur" },
  { id: "soundproof-rooms", group: "general", labelEn: "Soundproof rooms", labelFr: "Chambres insonorisées" },
  { id: "allergy-free-rooms", group: "general", labelEn: "Allergy-free rooms", labelFr: "Chambres anti-allergie" },
  { id: "entirely-non-smoking-property", group: "general", labelEn: "Entirely non-smoking property", labelFr: "Établissement entièrement non-fumeurs" },
  { id: "designated-smoking-area", group: "general", labelEn: "Designated smoking area", labelFr: "Espace fumeurs" },
  { id: "adults-only", group: "general", labelEn: "Adults only", labelFr: "Réservé aux adultes" },
  { id: "outdoor-furniture", group: "general", labelEn: "Outdoor furniture", labelFr: "Mobilier extérieur" },
  { id: "picnic-area", group: "general", labelEn: "Picnic area", labelFr: "Aire de pique-nique" },
  { id: "indoor-fireplace", group: "general", labelEn: "Indoor fireplace", labelFr: "Cheminée intérieure" },
  { id: "outdoor-fireplace", group: "general", labelEn: "Outdoor fireplace", labelFr: "Cheminée extérieure" },
  { id: "shared-kitchen", group: "general", labelEn: "Shared kitchen", labelFr: "Cuisine commune" },
  { id: "shared-lounge-tv-area", group: "general", labelEn: "Shared lounge / TV area", labelFr: "Salon commun/salle de télévision" },
  { id: "sun-loungers-or-beach-chairs", group: "general", labelEn: "Sun loungers or beach chairs", labelFr: "Chaises longues ou de plage" },
  { id: "sun-umbrellas", group: "general", labelEn: "Sun umbrellas", labelFr: "Parasols" },
  { id: "water-slide", group: "general", labelEn: "Water slide", labelFr: "Toboggan aquatique" },
  { id: "beach", group: "general", labelEn: "Beach", labelFr: "Plage" },
  { id: "safe", group: "general", labelEn: "Safe", labelFr: "Coffre-fort" },
  { id: "sauna", group: "wellness", labelEn: "Sauna", labelFr: "Sauna" },
  { id: "turkish-bath-hammam", group: "wellness", labelEn: "Turkish bath / hammam", labelFr: "Hammam" },
  { id: "hot-tub-jacuzzi", group: "wellness", labelEn: "Hot tub / jacuzzi", labelFr: "Bain à remous/jacuzzi" },
  { id: "steam-room", group: "wellness", labelEn: "Steam room", labelFr: "Bain à vapeur" },
  { id: "spa", group: "wellness", labelEn: "Spa", labelFr: "Spa" },
  { id: "spa-and-wellness-centre", group: "wellness", labelEn: "Spa and wellness centre", labelFr: "Spa et centre de bien-être" },
  { id: "spa-relaxation-area", group: "wellness", labelEn: "Spa / relaxation area", labelFr: "Coin spa/relaxation" },
  { id: "foot-bath", group: "wellness", labelEn: "Foot bath", labelFr: "Bain de pieds" },
  { id: "spa-wellness-packages", group: "wellness", labelEn: "Spa / wellness packages", labelFr: "Forfaits spa/bien-être" },
  { id: "massage-chair", group: "wellness", labelEn: "Massage chair", labelFr: "Fauteuil massant" },
  { id: "massages", group: "wellness", labelEn: "Massages", labelFr: "Massages" },
  { id: "beauty-services", group: "wellness", labelEn: "Beauty services", labelFr: "Services beauté" },
  { id: "hair-or-beauty-salon", group: "wellness", labelEn: "Hair or beauty salon", labelFr: "Salon de coiffure/institut de beauté" },
  { id: "solarium", group: "wellness", labelEn: "Solarium", labelFr: "Solarium" },
  { id: "thermal-bath-onsen", group: "wellness", labelEn: "Thermal bath / onsen", labelFr: "Bain thermal/onsen" },
  { id: "open-air-bath", group: "wellness", labelEn: "Open-air bath", labelFr: "Bain en plein air" },
  { id: "public-bath", group: "wellness", labelEn: "Public bath", labelFr: "Bain public" },
  { id: "fitness", group: "wellness", labelEn: "Fitness", labelFr: "Fitness" },
  { id: "fitness-centre", group: "wellness", labelEn: "Fitness centre", labelFr: "Centre de remise en forme" },
  { id: "fitness-classes", group: "wellness", labelEn: "Fitness classes", labelFr: "Cours de fitness" },
  { id: "yoga-classes", group: "wellness", labelEn: "Yoga classes", labelFr: "Cours de yoga" },
  { id: "personal-trainer", group: "wellness", labelEn: "Personal trainer", labelFr: "Coach sportif personnel" },
  { id: "gym-spa-changing-rooms", group: "wellness", labelEn: "Gym / spa changing rooms", labelFr: "Vestiaires salle de sport/spa" },
  { id: "breakfast", group: "food", labelEn: "Breakfast", labelFr: "Petit-déjeuner", paid: true },
  { id: "lunch", group: "food", labelEn: "Lunch", labelFr: "Déjeuner", paid: true },
  { id: "dinner", group: "food", labelEn: "Dinner", labelFr: "Dîner", paid: true },
  { id: "bar", group: "food", labelEn: "Bar", labelFr: "Bar" },
  { id: "snack-bar", group: "food", labelEn: "Snack bar", labelFr: "Snack-bar" },
  { id: "coffee-shop-on-site", group: "food", labelEn: "Coffee shop on site", labelFr: "Café sur place" },
  { id: "restaurant", group: "food", labelEn: "Restaurant", labelFr: "Restaurant" },
  { id: "breakfast-in-the-room", group: "food", labelEn: "Breakfast in the room", labelFr: "Petit-déjeuner en chambre" },
  { id: "room-service", group: "food", labelEn: "Room service", labelFr: "Service d'étage" },
  { id: "kids-meals", group: "food", labelEn: "Kids' meals", labelFr: "Menus enfants" },
  { id: "buffet-with-kids-options", group: "food", labelEn: "Buffet with kids' options", labelFr: "Buffet avec options enfants" },
  { id: "special-diet-menus-on-request", group: "food", labelEn: "Special diet menus (on request)", labelFr: "Menus pour régimes spéciaux (sur demande)" },
  { id: "wine-or-champagne", group: "food", labelEn: "Wine or champagne", labelFr: "Vin/champagne", paid: true },
  { id: "fruit", group: "food", labelEn: "Fruit", labelFr: "Fruits", paid: true },
  { id: "grocery-delivery", group: "food", labelEn: "Grocery delivery", labelFr: "Livraison de courses" },
  { id: "packed-lunches", group: "food", labelEn: "Packed lunches", labelFr: "Paniers-repas" },
  { id: "bbq-facilities", group: "food", labelEn: "BBQ facilities", labelFr: "Installations pour barbecue" },
  { id: "vending-machine-drinks", group: "food", labelEn: "Vending machine (drinks)", labelFr: "Distributeur automatique (boissons)" },
  { id: "vending-machine-snacks", group: "food", labelEn: "Vending machine (snacks)", labelFr: "Distributeur automatique (collations)" },
  { id: "meal-delivery-to-the-accommodation", group: "food", labelEn: "Meal delivery to the accommodation", labelFr: "Livraison de repas possible dans l'hébergement" },
  { id: "takeaway-breakfast-containers", group: "food", labelEn: "Takeaway breakfast containers", labelFr: "Récipients pour petit-déjeuner à emporter" },
  { id: "tennis-equipment", group: "activities", labelEn: "Tennis equipment", labelFr: "Matériel de tennis" },
  { id: "tennis-court", group: "activities", labelEn: "Tennis court", labelFr: "Court de tennis" },
  { id: "badminton-equipment", group: "activities", labelEn: "Badminton equipment", labelFr: "Matériel de badminton" },
  { id: "billiards", group: "activities", labelEn: "Billiards", labelFr: "Billard" },
  { id: "table-tennis", group: "activities", labelEn: "Table tennis", labelFr: "Tennis de table" },
  { id: "darts", group: "activities", labelEn: "Darts", labelFr: "Fléchettes" },
  { id: "squash", group: "activities", labelEn: "Squash", labelFr: "Squash" },
  { id: "bowling", group: "activities", labelEn: "Bowling", labelFr: "Bowling" },
  { id: "mini-golf", group: "activities", labelEn: "Mini golf", labelFr: "Minigolf" },
  { id: "golf-course-within-3-km", group: "activities", labelEn: "Golf course (within 3 km)", labelFr: "Parcours de golf (à moins de 3 km)" },
  { id: "archery", group: "activities", labelEn: "Archery", labelFr: "Tir à l'arc" },
  { id: "aerobics", group: "activities", labelEn: "Aerobics", labelFr: "Aérobic" },
  { id: "bingo", group: "activities", labelEn: "Bingo", labelFr: "Bingo" },
  { id: "karaoke", group: "activities", labelEn: "Karaoke", labelFr: "Karaoké" },
  { id: "water-park", group: "activities", labelEn: "Water park", labelFr: "Parc aquatique" },
  { id: "water-sports-facilities-on-site", group: "activities", labelEn: "Water sports facilities on site", labelFr: "Installations de sports nautiques sur place" },
  { id: "windsurfing", group: "activities", labelEn: "Windsurfing", labelFr: "Planche à voile" },
  { id: "diving", group: "activities", labelEn: "Diving", labelFr: "Plongée sous-marine" },
  { id: "snorkelling", group: "activities", labelEn: "Snorkelling", labelFr: "Plongée avec tuba" },
  { id: "canoeing", group: "activities", labelEn: "Canoeing", labelFr: "Canoë-kayak" },
  { id: "fishing", group: "activities", labelEn: "Fishing", labelFr: "Pêche" },
  { id: "horse-riding", group: "activities", labelEn: "Horse riding", labelFr: "Équitation" },
  { id: "cycling", group: "activities", labelEn: "Cycling", labelFr: "Cyclisme" },
  { id: "hiking", group: "activities", labelEn: "Hiking", labelFr: "Randonnée" },
  { id: "skiing", group: "activities", labelEn: "Skiing", labelFr: "Ski" },
  { id: "walking-tours", group: "activities", labelEn: "Walking tours", labelFr: "Balades à pied" },
  { id: "bike-tours", group: "activities", labelEn: "Bike tours", labelFr: "Visites à vélo" },
  { id: "temporary-art-galleries", group: "activities", labelEn: "Temporary art galleries", labelFr: "Galeries d'art temporaires" },
  { id: "bar-crawls", group: "activities", labelEn: "Bar crawls", labelFr: "Tournées des bars" },
  { id: "stand-up-comedy", group: "activities", labelEn: "Stand-up comedy", labelFr: "Spectacles d'humoristes" },
  { id: "movie-nights", group: "activities", labelEn: "Movie nights", labelFr: "Soirées film" },
  { id: "themed-dinner-nights", group: "activities", labelEn: "Themed dinner nights", labelFr: "Dîners à thème" },
  { id: "happy-hour", group: "activities", labelEn: "Happy hour", labelFr: "Happy hour" },
  { id: "local-culture-tour-or-class", group: "activities", labelEn: "Local culture tour or class", labelFr: "Visite ou cours autour de la culture locale" },
  { id: "cooking-class", group: "activities", labelEn: "Cooking class", labelFr: "Cours de cuisine" },
  { id: "live-music-performances", group: "activities", labelEn: "Live music / performances", labelFr: "Concerts/Spectacles" },
  { id: "live-sport-events-screening", group: "activities", labelEn: "Live sport events screening", labelFr: "Diffusion d'événements sportifs" },
  { id: "evening-entertainment", group: "activities", labelEn: "Evening entertainment", labelFr: "Animations en soirée" },
  { id: "nightclub-dj", group: "activities", labelEn: "Nightclub / DJ", labelFr: "Discothèque/DJ" },
  { id: "casino", group: "activities", labelEn: "Casino", labelFr: "Casino" },
  { id: "entertainment-team", group: "activities", labelEn: "Entertainment team", labelFr: "Équipe d'animation" },
  { id: "games-room", group: "activities", labelEn: "Games room", labelFr: "Salle de jeux" },
  { id: "chapel-shrine", group: "general", labelEn: "Chapel / place of worship", labelFr: "Chapelle/lieu de culte" },
  { id: "board-games-puzzles", group: "activities", labelEn: "Board games / puzzles", labelFr: "Jeux de société/puzzles" },
  { id: "parking", group: "transport", labelEn: "Parking", labelFr: "Parking" },
  { id: "bicycle-parking", group: "transport", labelEn: "Bicycle parking", labelFr: "Parking à vélos" },
  { id: "bicycle-rental", group: "transport", labelEn: "Bicycle rental", labelFr: "Location de vélos" },
  { id: "car-rental", group: "transport", labelEn: "Car rental", labelFr: "Location de voitures" },
  { id: "airport-shuttle", group: "transport", labelEn: "Airport shuttle", labelFr: "Navette aéroport", paid: true },
  { id: "shuttle-service", group: "transport", labelEn: "Shuttle service", labelFr: "Service de navette", paid: true },
  { id: "public-transport-tickets", group: "transport", labelEn: "Public transport tickets", labelFr: "Tickets de transports en commun", paid: true },
  { id: "24-hour-front-desk", group: "services", labelEn: "24-hour front desk", labelFr: "Réception ouverte 24h/24" },
  { id: "private-check-in-check-out", group: "services", labelEn: "Private check-in / check-out", labelFr: "Enregistrement/départ privé" },
  { id: "express-check-in-check-out", group: "services", labelEn: "Express check-in / check-out", labelFr: "Enregistrement/règlement rapide" },
  { id: "concierge-service", group: "services", labelEn: "Concierge service", labelFr: "Service de concierge" },
  { id: "tour-desk", group: "services", labelEn: "Tour desk", labelFr: "Bureau d'excursions" },
  { id: "currency-exchange", group: "services", labelEn: "Currency exchange", labelFr: "Service de change" },
  { id: "atm-on-site", group: "services", labelEn: "ATM on site", labelFr: "Distributeur automatique de billets sur place" },
  { id: "luggage-storage", group: "services", labelEn: "Luggage storage", labelFr: "Bagagerie" },
  { id: "lockers", group: "services", labelEn: "Lockers", labelFr: "Casiers" },
  { id: "invoice-provided-on-request", group: "services", labelEn: "Invoice provided on request", labelFr: "Facture fournie sur demande" },
  { id: "dry-cleaning", group: "services", labelEn: "Dry cleaning", labelFr: "Nettoyage à sec", paid: true },
  { id: "ironing-service", group: "services", labelEn: "Ironing service", labelFr: "Service de repassage", paid: true },
  { id: "laundry", group: "services", labelEn: "Laundry", labelFr: "Blanchisserie/laverie", paid: true },
  { id: "daily-housekeeping", group: "services", labelEn: "Daily housekeeping", labelFr: "Service de ménage quotidien" },
  { id: "trouser-press", group: "services", labelEn: "Trouser press", labelFr: "Presse à pantalons" },
  { id: "meeting-banquet-facilities", group: "services", labelEn: "Meeting / banquet facilities", labelFr: "Salles de réunion/réception" },
  { id: "business-centre", group: "services", labelEn: "Business centre", labelFr: "Centre d'affaires" },
  { id: "fax-photocopying", group: "services", labelEn: "Fax / photocopying", labelFr: "Fax/photocopies" },
  { id: "mini-market-on-site", group: "services", labelEn: "Mini-market on site", labelFr: "Supérette sur place" },
  { id: "cashless-payment-available", group: "services", labelEn: "Cashless payment available", labelFr: "Paiement sans espèces disponible" },
  { id: "mobile-app-for-room-service", group: "services", labelEn: "Mobile app for room service", labelFr: "Application mobile pour utiliser le service d'étage" },
  { id: "kids-club", group: "family", labelEn: "Kids' club", labelFr: "Club pour enfants" },
  { id: "children-s-playground", group: "family", labelEn: "Children's playground", labelFr: "Aire de jeux pour enfants" },
  { id: "indoor-play-area", group: "family", labelEn: "Indoor play area", labelFr: "Aire de jeux intérieure" },
  { id: "outdoor-play-equipment", group: "family", labelEn: "Outdoor play equipment", labelFr: "Jeux de plein air pour enfants" },
  { id: "babysitting-child-services", group: "family", labelEn: "Babysitting / child services", labelFr: "Garde d'enfants", paid: true },
  { id: "baby-safety-gates", group: "family", labelEn: "Baby safety gates", labelFr: "Barrières de sécurité pour bébés" },
  { id: "strollers", group: "family", labelEn: "Strollers", labelFr: "Poussettes" },
  { id: "pet-basket", group: "family", labelEn: "Pet basket", labelFr: "Panier pour animal de compagnie" },
  { id: "pet-bowls", group: "family", labelEn: "Pet bowls", labelFr: "Gamelles pour animaux de compagnie" },
  { id: "24-hour-security", group: "safety", labelEn: "24-hour security", labelFr: "Sécurité 24h/24" },
  { id: "security-alarm", group: "safety", labelEn: "Security alarm", labelFr: "Alarme de sécurité" },
  { id: "smoke-alarms", group: "safety", labelEn: "Smoke alarms", labelFr: "Détecteurs de fumée" },
  { id: "carbon-monoxide-detector", group: "safety", labelEn: "Carbon monoxide detector", labelFr: "Détecteur de monoxyde de carbone" },
  { id: "carbon-monoxide-sources", group: "safety", labelEn: "Carbon monoxide sources", labelFr: "Sources de monoxyde de carbone" },
  { id: "fire-extinguishers", group: "safety", labelEn: "Fire extinguishers", labelFr: "Extincteurs" },
  { id: "cctv-in-common-areas", group: "safety", labelEn: "CCTV in common areas", labelFr: "Caméras de surveillance dans les parties communes" },
  { id: "cctv-outside-the-property", group: "safety", labelEn: "CCTV outside the property", labelFr: "Caméras de surveillance à l'extérieur de l'établissement" },
  { id: "facilities-for-disabled-guests", group: "safety", labelEn: "Facilities for disabled guests", labelFr: "Équipements pour les personnes handicapées" },
  { id: "first-aid-kit-available", group: "safety", labelEn: "First aid kit available", labelFr: "Trousse de secours disponible" },
  { id: "health-professionals-available", group: "safety", labelEn: "Health professionals available", labelFr: "Professionnels de santé disponibles" },
  { id: "thermometers-provided-to-guests", group: "safety", labelEn: "Thermometers provided to guests", labelFr: "Thermomètres fournis aux clients par l'établissement" },
  { id: "face-masks-available-for-guests", group: "safety", labelEn: "Face masks available for guests", labelFr: "Masques à disposition des clients" },
  { id: "hand-sanitiser-in-the-accommodation-and-common-areas", group: "safety", labelEn: "Hand sanitiser in the accommodation and common areas", labelFr: "Gel hydroalcoolique dans l'hébergement et les pièces fréquentées" },
  { id: "physical-distancing-rules-followed", group: "safety", labelEn: "Physical distancing rules followed", labelFr: "Respect des règles de distanciation physique" },
  { id: "physical-barriers-or-screens-between-staff-and-guests", group: "safety", labelEn: "Physical barriers or screens between staff and guests", labelFr: "Barrières physiques ou écrans placés entre le personnel et les clients" },
  { id: "staff-follow-local-authority-safety-protocols", group: "safety", labelEn: "Staff follow local authority safety protocols", labelFr: "Le personnel respecte les protocoles de sécurité établis par les autorités locales" },
  { id: "physical-distancing-in-dining-areas", group: "safety", labelEn: "Physical distancing in dining areas", labelFr: "Distanciation physique dans les espaces repas" },
  { id: "accommodation-disinfected-between-stays", group: "cleaning", labelEn: "Accommodation disinfected between stays", labelFr: "Hébergement désinfecté après chaque séjour" },
  { id: "accommodation-sealed-after-cleaning", group: "cleaning", labelEn: "Accommodation sealed after cleaning", labelFr: "Hébergement fermé après le nettoyage" },
  { id: "cleaning-by-professional-cleaning-companies", group: "cleaning", labelEn: "Cleaning by professional cleaning companies", labelFr: "Le ménage est effectué par des sociétés de nettoyage professionnelles" },
  { id: "linen-and-towels-washed-per-local-guidelines", group: "cleaning", labelEn: "Linen and towels washed per local guidelines", labelFr: "Serviettes et linge de lit lavés selon les recommandations locales" },
  { id: "guests-can-opt-out-of-cleaning-during-the-stay", group: "cleaning", labelEn: "Guests can opt out of cleaning during the stay", labelFr: "Les clients peuvent refuser le service de nettoyage pendant leur séjour" },
  { id: "tableware-and-cutlery-disinfected", group: "cleaning", labelEn: "Tableware and cutlery disinfected", labelFr: "Vaisselle et couverts désinfectés" },
  { id: "delivered-food-sealed", group: "cleaning", labelEn: "Delivered food sealed", labelFr: "Protection hermétique des plats livrés" },
  { id: "use-of-cleaning-products-effective-against-coronavirus", group: "cleaning", labelEn: "Use of cleaning products effective against coronavirus", labelFr: "Utilisation de produits d'entretien efficaces contre le coronavirus" },
  { id: "shared-items-such-as-menus-magazines-and-pens-removed", group: "cleaning", labelEn: "Shared items such as menus, magazines and pens removed", labelFr: "Les accessoires partagés (menus, magazines, stylos) ont été retirés" },
  { id: "contactless-check-in-check-out", group: "access", labelEn: "Contactless check-in / check-out", labelFr: "Enregistrement et départ sans contact" },
  { id: "check-in-kiosk-in-the-lobby", group: "access", labelEn: "Check-in kiosk in the lobby", labelFr: "Borne d'enregistrement disponible dans le hall d'entrée" },
  { id: "keys-in-a-key-box-at-the-property", group: "access", labelEn: "Keys in a key box at the property", labelFr: "Clés disponibles dans une boîte à clés dans l'établissement" },
  { id: "keys-in-a-key-box-nearby", group: "access", labelEn: "Keys in a key box nearby", labelFr: "Clés disponibles dans une boîte à clés à proximité" },
  { id: "unlock-the-accommodation-with-a-phone-via-bluetooth", group: "access", labelEn: "Unlock the accommodation with a phone via Bluetooth", labelFr: "Ouverture du logement avec un smartphone par Bluetooth" },
  { id: "unlock-the-accommodation-with-a-phone-via-the-internet", group: "access", labelEn: "Unlock the accommodation with a phone via the internet", labelFr: "Ouverture du logement avec un smartphone via Internet" },
  { id: "unlock-the-accommodation-with-a-private-code", group: "access", labelEn: "Unlock the accommodation with a private code", labelFr: "Ouverture du logement avec un code confidentiel" },
  { id: "unlock-the-accommodation-by-scanning-a-qr-code", group: "access", labelEn: "Unlock the accommodation by scanning a QR code", labelFr: "Ouverture du logement en scannant un code QR" },
  { id: "unlock-the-accommodation-via-an-app", group: "access", labelEn: "Unlock the accommodation via an app", labelFr: "Ouverture du logement via une application" },
  { id: "access-the-property-via-bluetooth", group: "access", labelEn: "Access the property via Bluetooth", labelFr: "Accès à l'établissement par Bluetooth" },
  { id: "access-the-property-via-the-internet", group: "access", labelEn: "Access the property via the internet", labelFr: "Accès à l'établissement via Internet" },
  { id: "access-with-a-private-code", group: "access", labelEn: "Access with a private code", labelFr: "Accès avec un code confidentiel" },
  { id: "access-by-scanning-a-qr-code", group: "access", labelEn: "Access by scanning a QR code", labelFr: "Accès en scannant un code QR" },
  { id: "access-via-a-downloadable-app", group: "access", labelEn: "Access via a downloadable app", labelFr: "Accès via une application à télécharger" },
  { id: "access-keys", group: "access", labelEn: "Access keys", labelFr: "Clés d'accès" },
  { id: "access-cards", group: "access", labelEn: "Access cards", labelFr: "Cartes d'accès" },
  { id: "guest-id-details-collected-online-before-the-stay", group: "access", labelEn: "Guest ID details collected online before the stay", labelFr: "Informations d'identité collectées en ligne avant le séjour" },
  { id: "guest-health-screening", group: "access", labelEn: "Guest health screening", labelFr: "Contrôle de l'état de santé des clients" },
];

/** Demo logins created only when `SEED_DEMO_ACCOUNTS` is on. */
export const DEMO_ACCOUNTS = [
  { fullName: "Platform Admin", email: "admin@nestara.test", password: "Admin!2345", roles: ["admin", "guest"] },
  { fullName: "Hana Host", email: "host@nestara.test", password: "Host!2345", roles: ["host", "guest"] },
  { fullName: "Gabi Guest", email: "guest@nestara.test", password: "Guest!2345", roles: ["guest"] },
] as const;
