import type { Locale } from "@/i18n/translations";

export type HostOverviewCopy = typeof overviewCopy.en;

const overviewCopy = {
  en: {
    attention: "Needs your attention", allSet: "You’re all set", allSetBody: "Your listings and account are ready for guests.",
    pendingReview: "Listing pending review", rejected: "Listing needs changes", identity: "Identity verification is not finished", payouts: "Set up payouts", waitingRequests: "Requests waiting for a reply", unreadMessages: "Unread guest messages", unansweredMessages: "Guest messages waiting for a reply", unansweredReviews: "Reviews waiting for a reply",
    reviewStatus: "Review status", finishVerification: "View verification", setupPayouts: "Set up payouts", reply: "Reply", viewMessages: "View messages", review: "Reply to review",
    earned: "Earned", upcomingRevenue: "Upcoming", previousPeriod: "vs previous 30 days", noPreviousData: "No previous-period data", occupancyNext: "Next 30 days", occupancyComparison: "vs previous 30-day window", nightsBooked: "{booked} of {available} nights booked", reviewsCount: "{count} reviews", newRating: "New",
    upcomingActivity: "Upcoming activity", nextSevenDays: "Today and the next 7 days", checkIn: "Check-in", checkOut: "Check-out", noActivity: "No arrivals or departures in the next 7 days.", pendingRequests: "Pending requests", newestRequests: "Newest requests", viewAll: "View all", expiresIn: "Reply within {time}", expired: "Reply overdue", hours: "{count}h", days: "{count}d",
    revenueChart: "Revenue", revenueChartHint: "Six previous months and three upcoming months", actual: "Earned", forecast: "Confirmed upcoming", payout: "Pending payout", payoutHint: "Scheduled for transfer", managePayouts: "Manage payouts",
    listingsSnapshot: "Your listings", listingSnapshotHint: "Status, price and next reservation at a glance", noListings: "Create your first listing to start welcoming guests.", newListing: "Create listing", live: "Live", pending: "Pending review", draft: "Draft", rejectedStatus: "Rejected", nextBooking: "Next booking", noBooking: "No booking scheduled", edit: "Edit", calendar: "Calendar", viewPage: "View page",
    recentReviews: "Recent reviews", recentMessages: "Recent messages", noReviews: "No reviews yet.", noMessages: "No guest messages yet.", unread: "{count} unread", replyNeeded: "Reply needed", noBookingsTitle: "Ready for your first booking?", noBookingsBody: "A few small improvements can help guests find and choose your place.", addPhotos: "Add more high-quality photos", setWeekend: "Set a weekend price", enableSmart: "Enable smart pricing",
  },
  fr: {
    attention: "À traiter", allSet: "Tout est prêt", allSetBody: "Vos annonces et votre compte sont prêts à accueillir des voyageurs.", pendingReview: "Annonce en cours de validation", rejected: "Annonce à corriger", identity: "La vérification d’identité n’est pas terminée", payouts: "Configurer les versements", waitingRequests: "Demandes en attente de réponse", unreadMessages: "Messages voyageurs non lus", unansweredMessages: "Messages voyageurs en attente de réponse", unansweredReviews: "Avis en attente de réponse", reviewStatus: "Voir le statut", finishVerification: "Voir la vérification", setupPayouts: "Configurer", reply: "Répondre", viewMessages: "Voir les messages", review: "Répondre à l’avis", earned: "Gagné", upcomingRevenue: "À venir", previousPeriod: "par rapport aux 30 jours précédents", noPreviousData: "Aucune donnée précédente", occupancyNext: "30 prochains jours", occupancyComparison: "par rapport aux 30 jours précédents", nightsBooked: "{booked} nuits réservées sur {available}", reviewsCount: "{count} avis", newRating: "Nouveau", upcomingActivity: "Activité à venir", nextSevenDays: "Aujourd’hui et les 7 prochains jours", checkIn: "Arrivée", checkOut: "Départ", noActivity: "Aucune arrivée ou départ dans les 7 prochains jours.", pendingRequests: "Demandes en attente", newestRequests: "Demandes les plus récentes", viewAll: "Tout voir", expiresIn: "Répondre sous {time}", expired: "Réponse en retard", hours: "{count} h", days: "{count} j", revenueChart: "Revenus", revenueChartHint: "Six mois passés et trois mois à venir", actual: "Gagné", forecast: "Confirmé à venir", payout: "Versement en attente", payoutHint: "Programmé pour le transfert", managePayouts: "Gérer les versements", listingsSnapshot: "Vos annonces", listingSnapshotHint: "Statut, tarif et prochaine réservation", noListings: "Créez votre première annonce pour commencer à accueillir des voyageurs.", newListing: "Créer une annonce", live: "En ligne", pending: "En validation", draft: "Brouillon", rejectedStatus: "Refusée", nextBooking: "Prochaine réservation", noBooking: "Aucune réservation prévue", edit: "Modifier", calendar: "Calendrier", viewPage: "Voir l’annonce", recentReviews: "Avis récents", recentMessages: "Messages récents", noReviews: "Aucun avis pour le moment.", noMessages: "Aucun message voyageur.", unread: "{count} non lus", replyNeeded: "Réponse nécessaire", noBookingsTitle: "Prêt pour votre première réservation ?", noBookingsBody: "Quelques améliorations peuvent aider les voyageurs à choisir votre logement.", addPhotos: "Ajouter davantage de belles photos", setWeekend: "Définir un tarif week-end", enableSmart: "Activer la tarification intelligente",
  },
  es: {
    attention: "Necesita tu atención", allSet: "Todo listo", allSetBody: "Tus anuncios y tu cuenta están listos para recibir huéspedes.", pendingReview: "Anuncio pendiente de revisión", rejected: "El anuncio necesita cambios", identity: "La verificación de identidad no está terminada", payouts: "Configurar pagos", waitingRequests: "Solicitudes esperando respuesta", unreadMessages: "Mensajes de huéspedes sin leer", unansweredMessages: "Mensajes de huéspedes esperando respuesta", unansweredReviews: "Opiniones esperando respuesta", reviewStatus: "Ver estado", finishVerification: "Ver verificación", setupPayouts: "Configurar", reply: "Responder", viewMessages: "Ver mensajes", review: "Responder opinión", earned: "Ganado", upcomingRevenue: "Próximo", previousPeriod: "frente a los 30 días anteriores", noPreviousData: "Sin datos del periodo anterior", occupancyNext: "Próximos 30 días", occupancyComparison: "frente a los 30 días anteriores", nightsBooked: "{booked} de {available} noches reservadas", reviewsCount: "{count} opiniones", newRating: "Nuevo", upcomingActivity: "Próxima actividad", nextSevenDays: "Hoy y los próximos 7 días", checkIn: "Entrada", checkOut: "Salida", noActivity: "No hay entradas ni salidas en los próximos 7 días.", pendingRequests: "Solicitudes pendientes", newestRequests: "Solicitudes más recientes", viewAll: "Ver todas", expiresIn: "Responde en {time}", expired: "Respuesta atrasada", hours: "{count} h", days: "{count} d", revenueChart: "Ingresos", revenueChartHint: "Seis meses anteriores y tres próximos", actual: "Ganado", forecast: "Próximo confirmado", payout: "Pago pendiente", payoutHint: "Programado para transferencia", managePayouts: "Gestionar pagos", listingsSnapshot: "Tus anuncios", listingSnapshotHint: "Estado, precio y próxima reserva", noListings: "Crea tu primer anuncio para empezar a recibir huéspedes.", newListing: "Crear anuncio", live: "Activo", pending: "En revisión", draft: "Borrador", rejectedStatus: "Rechazado", nextBooking: "Próxima reserva", noBooking: "Sin reservas programadas", edit: "Editar", calendar: "Calendario", viewPage: "Ver anuncio", recentReviews: "Opiniones recientes", recentMessages: "Mensajes recientes", noReviews: "Aún no hay opiniones.", noMessages: "Aún no hay mensajes de huéspedes.", unread: "{count} sin leer", replyNeeded: "Respuesta pendiente", noBookingsTitle: "¿Listo para tu primera reserva?", noBookingsBody: "Unas pequeñas mejoras pueden ayudar a los huéspedes a elegir tu alojamiento.", addPhotos: "Añade más fotos de calidad", setWeekend: "Define un precio de fin de semana", enableSmart: "Activa los precios inteligentes",
  },
  de: {
    attention: "Ihre Aufgaben", allSet: "Alles bereit", allSetBody: "Ihre Unterkünfte und Ihr Konto sind bereit für Gäste.", pendingReview: "Unterkunft wird geprüft", rejected: "Unterkunft muss überarbeitet werden", identity: "Identitätsprüfung ist nicht abgeschlossen", payouts: "Auszahlungen einrichten", waitingRequests: "Anfragen warten auf Antwort", unreadMessages: "Ungelesene Gästenachrichten", unansweredMessages: "Gästenachrichten warten auf Antwort", unansweredReviews: "Bewertungen warten auf Antwort", reviewStatus: "Status ansehen", finishVerification: "Prüfung ansehen", setupPayouts: "Einrichten", reply: "Antworten", viewMessages: "Nachrichten ansehen", review: "Bewertung beantworten", earned: "Verdient", upcomingRevenue: "Bevorstehend", previousPeriod: "gegenüber den vorherigen 30 Tagen", noPreviousData: "Keine Daten aus dem Vorzeitraum", occupancyNext: "Nächste 30 Tage", occupancyComparison: "gegenüber dem vorherigen 30-Tage-Zeitraum", nightsBooked: "{booked} von {available} Nächten gebucht", reviewsCount: "{count} Bewertungen", newRating: "Neu", upcomingActivity: "Bevorstehende Aktivität", nextSevenDays: "Heute und die nächsten 7 Tage", checkIn: "Anreise", checkOut: "Abreise", noActivity: "Keine An- oder Abreisen in den nächsten 7 Tagen.", pendingRequests: "Offene Anfragen", newestRequests: "Neueste Anfragen", viewAll: "Alle ansehen", expiresIn: "Antwort in {time}", expired: "Antwort überfällig", hours: "{count} Std.", days: "{count} T.", revenueChart: "Umsatz", revenueChartHint: "Sechs vergangene und drei kommende Monate", actual: "Verdient", forecast: "Bestätigt bevorstehend", payout: "Ausstehende Auszahlung", payoutHint: "Zur Überweisung geplant", managePayouts: "Auszahlungen verwalten", listingsSnapshot: "Ihre Unterkünfte", listingSnapshotHint: "Status, Preis und nächste Buchung", noListings: "Erstellen Sie Ihre erste Unterkunft, um Gäste zu empfangen.", newListing: "Unterkunft erstellen", live: "Live", pending: "In Prüfung", draft: "Entwurf", rejectedStatus: "Abgelehnt", nextBooking: "Nächste Buchung", noBooking: "Keine Buchung geplant", edit: "Bearbeiten", calendar: "Kalender", viewPage: "Anzeige ansehen", recentReviews: "Neueste Bewertungen", recentMessages: "Neueste Nachrichten", noReviews: "Noch keine Bewertungen.", noMessages: "Noch keine Gästenachrichten.", unread: "{count} ungelesen", replyNeeded: "Antwort erforderlich", noBookingsTitle: "Bereit für Ihre erste Buchung?", noBookingsBody: "Einige kleine Verbesserungen helfen Gästen, Ihre Unterkunft zu wählen.", addPhotos: "Mehr hochwertige Fotos hinzufügen", setWeekend: "Wochenendpreis festlegen", enableSmart: "Intelligente Preise aktivieren",
  },
  pt: {
    attention: "Precisa da sua atenção", allSet: "Tudo pronto", allSetBody: "Os seus anúncios e a sua conta estão prontos para receber hóspedes.", pendingReview: "Anúncio em revisão", rejected: "O anúncio precisa de alterações", identity: "A verificação de identidade não está concluída", payouts: "Configurar pagamentos", waitingRequests: "Pedidos à espera de resposta", unreadMessages: "Mensagens de hóspedes por ler", unansweredMessages: "Mensagens de hóspedes à espera de resposta", unansweredReviews: "Avaliações à espera de resposta", reviewStatus: "Ver estado", finishVerification: "Ver verificação", setupPayouts: "Configurar", reply: "Responder", viewMessages: "Ver mensagens", review: "Responder à avaliação", earned: "Ganho", upcomingRevenue: "Próximo", previousPeriod: "face aos 30 dias anteriores", noPreviousData: "Sem dados do período anterior", occupancyNext: "Próximos 30 dias", occupancyComparison: "face ao período anterior de 30 dias", nightsBooked: "{booked} de {available} noites reservadas", reviewsCount: "{count} avaliações", newRating: "Novo", upcomingActivity: "Próxima atividade", nextSevenDays: "Hoje e os próximos 7 dias", checkIn: "Chegada", checkOut: "Partida", noActivity: "Sem chegadas ou partidas nos próximos 7 dias.", pendingRequests: "Pedidos pendentes", newestRequests: "Pedidos mais recentes", viewAll: "Ver todos", expiresIn: "Responda em {time}", expired: "Resposta atrasada", hours: "{count} h", days: "{count} d", revenueChart: "Receita", revenueChartHint: "Seis meses anteriores e três próximos", actual: "Ganho", forecast: "Próximo confirmado", payout: "Pagamento pendente", payoutHint: "Programado para transferência", managePayouts: "Gerir pagamentos", listingsSnapshot: "Os seus anúncios", listingSnapshotHint: "Estado, preço e próxima reserva", noListings: "Crie o seu primeiro anúncio para começar a receber hóspedes.", newListing: "Criar anúncio", live: "Ativo", pending: "Em revisão", draft: "Rascunho", rejectedStatus: "Rejeitado", nextBooking: "Próxima reserva", noBooking: "Sem reservas programadas", edit: "Editar", calendar: "Calendário", viewPage: "Ver anúncio", recentReviews: "Avaliações recentes", recentMessages: "Mensagens recentes", noReviews: "Ainda não há avaliações.", noMessages: "Ainda não há mensagens de hóspedes.", unread: "{count} por ler", replyNeeded: "Resposta necessária", noBookingsTitle: "Pronto para a primeira reserva?", noBookingsBody: "Algumas pequenas melhorias podem ajudar os hóspedes a escolher o seu alojamento.", addPhotos: "Adicione mais fotografias de qualidade", setWeekend: "Defina um preço de fim de semana", enableSmart: "Ative os preços inteligentes",
  },
} as const;

export function getHostOverviewCopy(locale: Locale): HostOverviewCopy {
  return overviewCopy[locale] as HostOverviewCopy;
}