import type { EnumDef } from "@/db/registry/types.js";

/** Values mirror the TypeScript unions in the front-end exactly. */
export const enums: EnumDef[] = [
  { name: "user_role", values: ["guest", "host", "admin", "moderator", "support", "accounting"] },
  { name: "booking_status", values: ["pending", "confirmed", "declined", "cancelled", "completed"] },
  { name: "listing_status", values: ["draft", "published", "suspended"] },
  {
    name: "property_category",
    values: [
      "apartment",
      "resort",
      "lodge",
      "hotel",
      "villa",
      "guesthouse",
      "riad",
      "studio",
      "bungalow",
      "chalet",
      "hostel",
      "camping",
    ],
  },
  {
    name: "amenity_id",
    values: ["wifi", "pool", "kitchen", "parking", "airConditioning", "workspace", "petFriendly", "breakfast"],
  },
  { name: "cancellation_policy", values: ["flexible", "moderate", "strict"] },
  {
    name: "equipment_group",
    values: ["general", "wellness", "food", "activities", "transport", "services", "family", "safety", "cleaning", "access"],
  },
  { name: "discount_kind", values: ["longStay", "mobile", "lastMinute", "weekend"] },
  { name: "payment_method", values: ["card"] },
  { name: "card_brand", values: ["visa", "mastercard", "amex", "card"] },
  { name: "payment_status", values: ["pending", "authorized", "paid", "refunded", "failed"] },
  { name: "payout_status", values: ["paid", "scheduled"] },
  { name: "team_scope", values: ["calendar", "messaging"] },
  { name: "cookie_choice", values: ["accepted", "essential"] },
  { name: "actor_role", values: ["guest", "host", "admin", "system"] },
  {
    name: "moderation_action",
    values: [
      "review_hidden",
      "review_restored",
      "review_deleted",
      "user_suspended",
      "user_restored",
      "listing_suspended",
      "listing_published",
      "listing_approved",
      "listing_rejected",
      "settings_updated",
      "role_granted",
      "role_revoked",
      "payout_created",
      "payout_paid",
      "user_verification_updated",
      "user_banned",
      "user_unbanned",
      "listing_report_resolved",
      "listing_report_dismissed",
      "booking_cancelled_admin",
      "booking_refunded",
      "booking_modified",
      "ticket_assigned",
      "ticket_status_changed",
      "ticket_action_taken",
      "commission_updated",
      "account_deleted",
    ],
  },
  {
    name: "report_reason",
    values: ["fraud", "inappropriate", "wrong_information", "unavailable", "safety", "other"],
  },
  { name: "report_status", values: ["open", "reviewing", "resolved", "dismissed"] },
  { name: "ticket_status", values: ["open", "pending", "awaiting_reply", "escalated", "resolved", "closed"] },
  { name: "ticket_priority", values: ["low", "normal", "high", "urgent"] },
  {
    name: "ticket_category",
    values: ["booking", "payment", "listing", "account", "dispute", "other"],
  },
  { name: "verification_status", values: ["pending", "verified", "rejected"] },
  { name: "notification_status", values: ["queued", "sending", "sent", "failed"] },
];

