/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DevAdminRouteImport } from './routes/dev-admin'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HostRouteImport } from './routes/host'
import { Route as ListYourPlaceRouteImport } from './routes/list-your-place'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysPropertyIdRouteImport } from './routes/stays.$propertyId'
import { Route as AdminHostsUserIdRouteImport } from './routes/admin_.hosts.$userId'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin_.listings.$listingId'
import { Route as ApiPublicExchangeRatesRouteImport } from './routes/api/public/exchange-rates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAdminRoute = DevAdminRouteImport.update({
  id: '/dev-admin',
  path: '/dev-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourPlaceRoute = ListYourPlaceRouteImport.update({
  id: '/list-your-place',
  path: '/list-your-place',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/stays/',
  path: '/stays/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysPropertyIdRoute = StaysPropertyIdRouteImport.update({
  id: '/stays/$propertyId',
  path: '/stays/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHostsUserIdRoute = AdminHostsUserIdRouteImport.update({
  id: '/admin_/hosts/$userId',
  path: '/admin/hosts/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/admin_/listings/$listingId',
  path: '/admin/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExchangeRatesRoute = ApiPublicExchangeRatesRouteImport.update({
  id: '/api/public/exchange-rates',
  path: '/api/public/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dev-admin': typeof DevAdminRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/host': typeof HostRoute
  '/list-your-place': typeof ListYourPlaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/': typeof StaysIndexRoute
  '/admin/hosts/$userId': typeof AdminHostsUserIdRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/api/public/exchange-rates': typeof ApiPublicExchangeRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dev-admin': typeof DevAdminRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/host': typeof HostRoute
  '/list-your-place': typeof ListYourPlaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays': typeof StaysIndexRoute
  '/admin/hosts/$userId': typeof AdminHostsUserIdRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/api/public/exchange-rates': typeof ApiPublicExchangeRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dev-admin': typeof DevAdminRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/host': typeof HostRoute
  '/list-your-place': typeof ListYourPlaceRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/': typeof StaysIndexRoute
  '/admin_/hosts/$userId': typeof AdminHostsUserIdRoute
  '/admin_/listings/$listingId': typeof AdminListingsListingIdRoute
  '/api/public/exchange-rates': typeof ApiPublicExchangeRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dev-admin'
    | '/favourites'
    | '/forgot-password'
    | '/help'
    | '/host'
    | '/list-your-place'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/trips'
    | '/booking/$bookingId'
    | '/stays/$propertyId'
    | '/stays/'
    | '/admin/hosts/$userId'
    | '/admin/listings/$listingId'
    | '/api/public/exchange-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dev-admin'
    | '/favourites'
    | '/forgot-password'
    | '/help'
    | '/host'
    | '/list-your-place'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/trips'
    | '/booking/$bookingId'
    | '/stays/$propertyId'
    | '/stays'
    | '/admin/hosts/$userId'
    | '/admin/listings/$listingId'
    | '/api/public/exchange-rates'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dev-admin'
    | '/favourites'
    | '/forgot-password'
    | '/help'
    | '/host'
    | '/list-your-place'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/trips'
    | '/booking/$bookingId'
    | '/stays/$propertyId'
    | '/stays/'
    | '/admin_/hosts/$userId'
    | '/admin_/listings/$listingId'
    | '/api/public/exchange-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DevAdminRoute: typeof DevAdminRoute
  FavouritesRoute: typeof FavouritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HostRoute: typeof HostRoute
  ListYourPlaceRoute: typeof ListYourPlaceRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TripsRoute: typeof TripsRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  StaysPropertyIdRoute: typeof StaysPropertyIdRoute
  StaysIndexRoute: typeof StaysIndexRoute
  AdminHostsUserIdRoute: typeof AdminHostsUserIdRoute
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
  ApiPublicExchangeRatesRoute: typeof ApiPublicExchangeRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-admin': {
      id: '/dev-admin'
      path: '/dev-admin'
      fullPath: '/dev-admin'
      preLoaderRoute: typeof DevAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-place': {
      id: '/list-your-place'
      path: '/list-your-place'
      fullPath: '/list-your-place'
      preLoaderRoute: typeof ListYourPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/stays'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$propertyId': {
      id: '/stays/$propertyId'
      path: '/stays/$propertyId'
      fullPath: '/stays/$propertyId'
      preLoaderRoute: typeof StaysPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/hosts/$userId': {
      id: '/admin_/hosts/$userId'
      path: '/admin/hosts/$userId'
      fullPath: '/admin/hosts/$userId'
      preLoaderRoute: typeof AdminHostsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/listings/$listingId': {
      id: '/admin_/listings/$listingId'
      path: '/admin/listings/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exchange-rates': {
      id: '/api/public/exchange-rates'
      path: '/api/public/exchange-rates'
      fullPath: '/api/public/exchange-rates'
      preLoaderRoute: typeof ApiPublicExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DevAdminRoute: DevAdminRoute,
  FavouritesRoute: FavouritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HostRoute: HostRoute,
  ListYourPlaceRoute: ListYourPlaceRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TripsRoute: TripsRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  StaysPropertyIdRoute: StaysPropertyIdRoute,
  StaysIndexRoute: StaysIndexRoute,
  AdminHostsUserIdRoute: AdminHostsUserIdRoute,
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
  ApiPublicExchangeRatesRoute: ApiPublicExchangeRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
